import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function fillFood(page: Page, name = 'Crema ai tartufi di prova') {
  await page.getByRole('button', { name: 'Nuovo alimento' }).click()
  await page.getByLabel('Nome alimento', { exact: true }).fill(name)
  await page.getByLabel('Energia (kcal)', { exact: true }).fill('123')
  await page.getByLabel('Proteine (g)', { exact: true }).fill('10')
  await page.getByLabel('Carboidrati (g)', { exact: true }).fill('20')
  await page.getByLabel('Grassi (g)', { exact: true }).fill('3')
  await page.getByLabel('Riferimento della fonte', { exact: true }).fill('Valori fittizi per test')
}

test('catalogo e ricetta: quantità, esclusioni, fonti, revisioni e archiviazione persistono', async ({ page }) => {
  await page.goto('/#catalogo')
  await expect(page.getByRole('heading', { name: 'Il tuo primo alimento' })).toBeVisible()
  await fillFood(page)
  await page.getByRole('button', { name: 'Aggiungi porzione' }).click()
  await page.getByLabel('Etichetta porzione 1', { exact: true }).fill('Porzione test')
  await page.getByLabel('Quantità porzione 1 (g)', { exact: true }).fill('30')
  await page.getByLabel('Fonte conversione 1', { exact: true }).fill('Pesata fittizia')
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await expect(page.getByRole('status')).toContainText('Alimento salvato')
  const food = page.getByRole('article')
  await expect(food).toContainText('Contiene alimenti esclusi: tartufo')
  await expect(food).toContainText('Non disponibile')
  await food.getByText('Calcola per una quantità', { exact: true }).click()
  await page.getByLabel('Quantità da calcolare').fill('1,5')
  await page.getByLabel('Unità da calcolare').selectOption('portion:0')
  await expect(food).toContainText('55,35')
  await page.getByLabel('Unità da calcolare').selectOption('ml')
  await expect(food.getByRole('status')).toContainText('Conversione non disponibile')
  await page.getByRole('button', { name: 'Ricette', exact: true }).click()
  await page.getByRole('button', { name: 'Nuova ricetta' }).click()
  await page.getByLabel('Nome ricetta').fill('Preparazione di prova')
  await page.getByLabel('Alimento da aggiungere').selectOption({ label: 'Crema ai tartufi di prova' })
  await page.getByLabel('Quantità ingrediente').fill('1,5')
  await page.getByLabel('Unità ingrediente').selectOption('portion:0')
  await page.getByRole('button', { name: 'Aggiungi ingrediente' }).click()
  await page.getByLabel('Resa finale').fill('90')
  await page.getByLabel('Istruzioni (facoltative)').fill('<script>window.testExecuted = true</script>')
  await expect(page.getByText('Totale ricetta · 90 g')).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: 'test-results/recipe-form-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Salva ricetta' }).click()
  await expect(page.getByRole('status')).toContainText('Ricetta salvata')
  await expect(page.getByRole('article')).toContainText('55,35')
  await page.getByRole('button', { name: 'Alimenti', exact: true }).click()
  await page.getByRole('button', { name: 'Modifica alimento' }).click()
  await page.getByLabel('Energia (kcal)', { exact: true }).fill('999')
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await page.getByRole('button', { name: 'Archivia', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Elemento archiviato')
  await page.reload()
  await page.getByRole('button', { name: 'Ricette', exact: true }).click()
  await expect(page.getByRole('article')).toContainText('55,35')
  await page.getByText('Ingredienti, fonti e preparazione', { exact: true }).click()
  await expect(page.getByRole('article')).toContainText('Pesata fittizia')
  await expect(page.getByRole('article')).toContainText('<script>window.testExecuted = true</script>')
  expect(await page.evaluate(() => 'testExecuted' in window)).toBe(false)
  await page.getByRole('button', { name: 'Modifica ricetta' }).click()
  await page.getByLabel('Nome ricetta').fill('Preparazione aggiornata')
  await page.getByLabel('Quantità ingrediente 1 (porzioni)', { exact: true }).fill('3')
  await page.getByRole('button', { name: 'Salva ricetta' }).click()
  await expect(page.getByRole('article')).toContainText('110,7')
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: 'test-results/catalog-320.png', fullPage: true })
  await page.getByRole('button', { name: 'Archivia', exact: true }).click()
  await page.getByLabel('Mostra archiviati').check()
  await expect(page.getByRole('article')).toContainText('Preparazione aggiornata')
  await page.getByRole('button', { name: 'Ripristina', exact: true }).click()
  await page.getByLabel('Mostra archiviati').uncheck()
  await expect(page.getByRole('article')).toContainText('Preparazione aggiornata')
})

test('form alimento a 320 px, input invalidi e recupero quota senza perdere input', async ({ page }) => {
  await page.addInitScript(() => {
    const original = IDBObjectStore.prototype.put
    Object.defineProperty(window, 'testQuota', { value: true, writable: true })
    IDBObjectStore.prototype.put = function (...args) {
      if (this.name === 'foods' && Reflect.get(window, 'testQuota')) throw new DOMException('quota', 'QuotaExceededError')
      return original.apply(this, args)
    }
  })
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto('/#catalogo')
  await fillFood(page, 'Alimento di prova')
  await page.getByLabel('URL fonte (facoltativo)').fill('javascript:alert(1)')
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await expect(page.getByRole('alert')).toContainText('Controlla i campi')
  await expect(page.getByLabel('URL fonte (facoltativo)')).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('URL fonte (facoltativo)').fill('')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: 'test-results/food-form-320.png', fullPage: true })
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await expect(page.getByRole('alert')).toContainText('Spazio del browser esaurito')
  await expect(page.getByLabel('Nome alimento', { exact: true })).toHaveValue('Alimento di prova')
  await page.evaluate(() => { Reflect.set(window, 'testQuota', false) })
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await expect(page.getByRole('status')).toContainText('Alimento salvato')
})
