import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { createFood, createSelectedPlan } from './helpers'

test('consumi indipendenti, peso e storico dopo modifica menù/catalogo; cambio previsto confermato', async ({ page }) => {
  await createFood(page)
  await createSelectedPlan(page)
  await page.getByRole('navigation').getByRole('link', { name: 'Oggi', exact: true }).click()
  await expect(page.getByText('Diario assente · nessun consumo o peso registrato.')).toBeVisible()
  await page.getByRole('button', { name: 'Apri diario della giornata' }).click()
  await expect(page.getByText('Non registrato · nessuno zero implicito.')).toBeVisible()
  await page.getByRole('button', { name: 'Copia esplicitamente il piano nei consumi' }).click()
  await page.getByRole('button', { name: 'Copia esplicitamente il piano nei consumi' }).click()
  const consumed = page.getByRole('region', { name: 'Consumato Colazione', exact: true }), planned = page.getByRole('region', { name: 'Colazione', exact: true })
  await expect(consumed.getByLabel('Quantità consumata 1 (g)')).toHaveCount(1)
  await consumed.getByLabel('Quantità consumata 1 (g)').fill('50')
  await consumed.getByRole('button', { name: 'Applica quantità' }).click()
  await expect(planned).toContainText('100 g')
  await expect(consumed).toContainText('50 g')
  await page.getByLabel('Peso (kg, facoltativo)').fill('87,5')
  await page.getByRole('button', { name: 'Aggiungi attività' }).click()
  await page.getByLabel('Attività 1', { exact: true }).fill('Attività fittizia')
  await page.getByLabel('Durata attività 1 (minuti, facoltativa)').fill('20')
  await page.getByLabel('Fame (facoltativo)').selectOption('3')
  await page.getByLabel('Energia percepita (facoltativo)').selectOption('4')
  await page.getByLabel('Umore (facoltativo)').selectOption('2')
  await page.getByLabel('Note della giornata (facoltative)').fill('<script>window.diaryExecuted = true</script>')
  await page.getByLabel('Stato della giornata').selectOption('complete')
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByRole('status')).toContainText('Giornata salvata')
  await page.reload()
  await page.getByLabel('Data selezionata').fill('2026-09-10')
  await expect(page.getByLabel('Peso (kg, facoltativo)')).toHaveValue('87.5')
  await expect(consumed).toContainText('61,5')
  await expect(page.getByLabel('Attività 1', { exact: true })).toHaveValue('Attività fittizia')
  await page.getByRole('navigation').getByRole('link', { name: 'Menù', exact: true }).click()
  await page.getByLabel('Piano e revisione da consultare').selectOption({ label: 'Piano fittizio · Revisione 1 · 2026-09-10 / 2026-09-10' })
  await page.getByRole('button', { name: 'Modifica con nuova revisione' }).click()
  await planned.getByLabel('Quantità voce 1 (g)').fill('200')
  await planned.getByRole('button', { name: 'Applica quantità' }).click()
  await page.getByRole('button', { name: 'Salva revisione del menù' }).click()
  await expect(page.getByRole('status')).toContainText('Menù salvato')
  await page.getByRole('button', { name: 'Usa questa revisione per 2026-09-10' }).click()
  await expect(page.getByRole('status')).toContainText('Piano selezionato')
  await page.getByRole('navigation').getByRole('link', { name: 'Alimenti / Ricette' }).click()
  await page.getByRole('button', { name: 'Modifica alimento' }).click()
  await page.getByLabel('Energia (kcal)', { exact: true }).fill('999')
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await expect(page.getByRole('status')).toContainText('Alimento salvato')
  await page.getByRole('button', { name: 'Archivia', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Elemento archiviato')
  await page.getByRole('navigation').getByRole('link', { name: 'Diario', exact: true }).click()
  await expect(page.locator('main')).toContainText('Piano fittizio · Revisione 1')
  await expect(planned).toContainText('100 g'); await expect(consumed).toContainText('50 g')
  await expect(page.getByLabel('Peso (kg, facoltativo)')).toHaveValue('87.5')
  expect(await page.evaluate(() => 'diaryExecuted' in window)).toBe(false)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('heading', { level: 1 }).focus()
  await page.screenshot({ path: 'test-results/diary-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('heading', { level: 1 }).focus()
  await page.screenshot({ path: 'test-results/diary-320.png', fullPage: true })
  await consumed.screenshot({ path: 'test-results/diary-consumed-320.png' })
  await page.getByLabel('Peso (kg, facoltativo)').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/diary-weight-320.png' })
  await page.getByText('Cambia il riferimento al piano storico', { exact: true }).focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Nuovo piano storico')).toBeFocused()
  await page.getByLabel('Nuovo piano storico').selectOption({ label: 'Piano fittizio · Revisione 2' })
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Conferma cambio del piano storico' }).click()
  await expect(planned).toContainText('100 g')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Conferma cambio del piano storico' }).click()
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByRole('status')).toContainText('Giornata salvata')
  await expect(planned).toContainText('200 g'); await expect(consumed).toContainText('50 g')
  await page.getByLabel('Data selezionata').fill('2026-09-09')
  await expect(page.getByText('Diario assente · nessun consumo o peso registrato.')).toBeVisible()
  await page.getByRole('button', { name: '2026-09-10', exact: true }).click()
  await expect(page.getByLabel('Stato della giornata')).toHaveValue('complete')
  await expect(planned).toContainText('200 g')
})

test('esclusi consumabili, input invalidi, rollback quota, peso unico e cancellazione confermata', async ({ page }) => {
  await page.addInitScript(() => { const original = IDBObjectStore.prototype.put; Reflect.set(window, 'testDiaryQuota', true); IDBObjectStore.prototype.put = function (...args) { if (this.name === 'bodyMeasurements' && Reflect.get(window, 'testDiaryQuota')) throw new DOMException('quota', 'QuotaExceededError'); return original.apply(this, args) } })
  await createFood(page, 'Tartufo fittizio')
  await page.getByRole('navigation').getByRole('link', { name: 'Diario', exact: true }).click()
  await page.getByLabel('Data selezionata').fill('2026-09-10')
  await page.getByRole('button', { name: 'Apri diario della giornata' }).click()
  const consumed = page.getByRole('region', { name: 'Consumato Colazione', exact: true })
  await consumed.getByText('Registra un alimento o una ricetta', { exact: true }).click()
  await consumed.getByLabel('Alimento o ricetta').selectOption({ label: 'Tartufo fittizio · alimento' })
  await consumed.getByRole('button', { name: 'Aggiungi consumo' }).click()
  await page.getByLabel('Peso (kg, facoltativo)').fill('0')
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByLabel('Peso (kg, facoltativo)')).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Peso (kg, facoltativo)').fill('80,5')
  await page.getByLabel('Note della giornata (facoltative)').fill('Conserva questi input fittizi')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('navigation').getByRole('link', { name: 'Menù', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Diario')
  await expect(page.getByLabel('Note della giornata (facoltative)')).toHaveValue('Conserva questi input fittizi')
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByRole('alert')).toContainText('Spazio del browser esaurito')
  await expect(page.getByLabel('Note della giornata (facoltative)')).toHaveValue('Conserva questi input fittizi')
  expect(await page.evaluate(async () => { const db = await new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open('fatreduction'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) }); const count = await new Promise<number>(resolve => { const r = db.transaction('dailyDiaries').objectStore('dailyDiaries').count(); r.onsuccess = () => resolve(r.result) }); db.close(); return count })).toBe(0)
  await page.setViewportSize({ width: 320, height: 800 })
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.evaluate(() => Reflect.set(window, 'testDiaryQuota', false))
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByRole('status')).toContainText('Giornata salvata')
  await page.getByLabel('Peso (kg, facoltativo)').fill('79,5')
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByRole('status')).toContainText('Giornata salvata')
  await page.reload(); await page.getByLabel('Data selezionata').fill('2026-09-10')
  await expect(page.getByLabel('Peso (kg, facoltativo)')).toHaveValue('79.5')
  await expect(page.getByRole('button', { name: '2026-09-10', exact: true })).toHaveCount(1)
  page.once('dialog', dialog => dialog.dismiss())
  await consumed.getByRole('button', { name: 'Rimuovi consumo' }).click()
  await expect(consumed.getByLabel('Quantità consumata 1 (g)')).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await consumed.getByRole('button', { name: 'Rimuovi consumo' }).click()
  await page.getByLabel('Peso (kg, facoltativo)').fill('')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Salva giornata' }).click()
  await expect(page.getByRole('status')).toContainText('Giornata salvata')
  await expect(page.getByText('Non registrato · nessuno zero implicito.')).toBeVisible()
  await page.getByLabel('Data selezionata').fill('2099-01-01')
  await expect(page.getByText('Data futura: puoi consultare il piano; consumi e peso si registrano fino a oggi.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Apri diario della giornata' })).toHaveCount(0)
})
