import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

export async function createFood(page: Page, name = 'Alimento fittizio') {
  await page.goto('/#catalogo')
  await page.getByRole('button', { name: 'Nuovo alimento' }).click()
  await page.getByLabel('Nome alimento', { exact: true }).fill(name)
  for (const [label, value] of [['Energia (kcal)', '123'], ['Proteine (g)', '10'], ['Carboidrati (g)', '20'], ['Grassi (g)', '3']]) await page.getByLabel(label, { exact: true }).fill(value)
  await page.getByLabel('Riferimento della fonte', { exact: true }).fill('Fixture fittizia per test')
  await page.getByRole('button', { name: 'Salva alimento' }).click()
  await expect(page.getByRole('status')).toContainText('Alimento salvato')
}
test('menù settimana: esclusioni, alternativa, revisione, scelta per data e reload a 320 px', async ({ page }) => {
  await createFood(page, 'Tartufo fittizio')
  await createFood(page)
  await page.getByRole('navigation').getByRole('link', { name: 'Menù', exact: true }).click()
  await page.getByLabel('Titolo del piano').fill('Settimana fittizia')
  await page.getByLabel('Inizio del piano').fill('2026-09-10')
  await page.getByLabel('Durata del piano').selectOption('7')
  await page.getByRole('button', { name: 'Crea bozza del menù' }).click()
  await expect(page.locator('.meal-card')).toHaveCount(5)
  const breakfast = page.getByRole('region', { name: 'Colazione', exact: true })
  await breakfast.getByText('Aggiungi alimenti o alternative', { exact: true }).click()
  await expect(breakfast.getByLabel('Alimento o ricetta').locator('option')).toHaveCount(2)
  await breakfast.getByLabel('Alimento o ricetta').selectOption({ label: 'Alimento fittizio · alimento' })
  await breakfast.getByRole('button', { name: 'Aggiungi al pasto' }).click()
  await breakfast.getByLabel('Aggiungi come alternativa non conteggiata').check()
  await breakfast.getByLabel('Quantità da aggiungere').fill('50')
  await breakfast.getByRole('button', { name: 'Aggiungi alternativa' }).click()
  await breakfast.getByLabel('Voce da sostituire · Colazione').selectOption({ label: 'Alimento fittizio' })
  await breakfast.getByRole('button', { name: 'Usa questa alternativa' }).click()
  await breakfast.getByLabel('Note Colazione (facoltative)').fill('Nota fittizia')
  await page.getByRole('button', { name: 'Salva revisione del menù' }).click()
  await expect(page.getByRole('status')).toContainText('Menù salvato')
  await page.getByRole('button', { name: 'Usa questa revisione per 2026-09-10' }).click()
  await expect(page.getByRole('status')).toContainText('Piano selezionato')
  await page.getByRole('button', { name: 'Settimana', exact: true }).click()
  await expect(page.locator('.meal-card')).toHaveCount(35)
  await page.getByRole('button', { name: 'Giorno', exact: true }).click()
  await page.getByRole('button', { name: 'Modifica con nuova revisione' }).click()
  const quantity = breakfast.getByLabel('Quantità voce 1 (g)')
  await quantity.fill('75,5')
  await breakfast.getByRole('button', { name: 'Applica quantità' }).click()
  await page.getByRole('button', { name: 'Salva revisione del menù' }).click()
  await expect(page.getByRole('status')).toContainText('Menù salvato')
  await page.reload()
  await page.getByLabel('Data selezionata').fill('2026-09-10')
  await page.getByLabel('Piano e revisione da consultare').selectOption({ label: 'Settimana fittizia · Revisione 1 · 2026-09-10 / 2026-09-16' })
  await expect(breakfast).toContainText('50 g')
  await expect(breakfast).toContainText('61,5')
  await page.getByRole('navigation').getByRole('link', { name: 'Oggi', exact: true }).click()
  await expect(page.getByLabel('Data selezionata')).toHaveValue('2026-09-10')
  await expect(page.locator('main')).toContainText('Revisione 1')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: 'test-results/menu-today-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/menu-today-320.png', fullPage: true })
  await page.getByLabel('Data selezionata').focus()
  // Il controllo data nativo attraversa giorno, mese, anno e calendario con Tab.
  for (let n = 0; n < 6 && !await page.getByRole('button', { name: 'Torna a oggi' }).evaluate(el => el === document.activeElement); n++) await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Torna a oggi' })).toBeFocused()
})

test('quota menù: bozza conservata e nuovo tentativo', async ({ page }) => {
  await page.addInitScript(() => { const original = IDBObjectStore.prototype.add; Reflect.set(window, 'testQuota', true); IDBObjectStore.prototype.add = function (...args) { if (this.name === 'plannedMeals' && Reflect.get(window, 'testQuota')) throw new DOMException('quota', 'QuotaExceededError'); return original.apply(this, args) } })
  await page.goto('/#menu')
  await page.getByLabel('Titolo del piano').fill('Bozza fittizia')
  await page.getByRole('button', { name: 'Crea bozza del menù' }).click()
  await page.getByLabel('Note Colazione (facoltative)').fill('Conserva nota fittizia')
  await page.getByRole('button', { name: 'Salva revisione del menù' }).click()
  await expect(page.getByRole('alert')).toContainText('Spazio del browser esaurito')
  await expect(page.getByLabel('Note Colazione (facoltative)')).toHaveValue('Conserva nota fittizia')
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: 'test-results/menu-form-320.png', fullPage: true })
  await page.evaluate(() => Reflect.set(window, 'testQuota', false))
  await page.getByRole('button', { name: 'Salva revisione del menù' }).click()
  await expect(page.getByRole('status')).toContainText('Menù salvato')
})
